/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FlexSpace: typeof import('./../src/components/common/FlexSpace.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconSelect: typeof import('./../src/components/common/IconSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./../src/components/common/SchemaForm/index.vue')['default']
    SvgIcon: typeof import('./../src/components/common/SvgIcon.vue')['default']
  }
}
